name: Publish NuGet

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Update to your .NET version

    - name: Create NuGet.Config
      run: |
    - name: Configure NuGet
      run: |
        cat > NuGet.Config << EOF
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <clear />
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
            <add key="github" value="https://nuget.pkg.github.com/LazyMagicOrg/index.json" />
          </packageSources>
          <packageSourceCredentials>
            <github>
              <add key="Username" value="USERNAME" />
              <add key="ClearTextPassword" value="${{ secrets.GITHUB_TOKEN }}" />
            </github>
          </packageSourceCredentials>
        </configuration>
        EOF

        cat nuget.config
        

    - name: Restore dependencies
      run: dotnet restore

    - name: Build # Build solution
      run: dotnet build --no-restore

    - name: Publish
      run: |
        dotnet nuget push ./Packages/*.nupkg --source https://nuget.pkg.github.com/LazyMagicOrg/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
        dotnet nuget push ./Packages/*.snupkg --source https://nuget.pkg.github.com/LazyMagicOrg/index.json --api-key ${{ secrets.GITHUB_TOKEN }}